### ISSUE TITLE
make changes to plist part of plugin parameters

### ISSUE THREAD

**Issue by jlooper** [AntonioCuevaUrraco/nativescript-facebook-login#1]
Great plugin! 

It would be nice not to have to edit the Android manifest or the iOS plist, so as to make the app easier to upgrade. Could you create a way to send the app id and name via parameters in the package.json file to the plugin, so we don't have to edit the platform files?

thanks!

**Comment by jlooper** [comment]
We've opened a github issue to make this easier within the {N} framework as you have to edit these files for any customize job...

**Comment by AntonioCuevaUrraco** [comment]
That's perfect also to add the .aar as a  gradle dependency instead of distribute the library would make things easier to create plugins.

**Comment by francorobles** [comment]
Does this work in iOS 11+? Because after login it just restarts my app back to initial screen. :(

**Comment by AntonioCuevaUrraco** [comment]
@francorobles Can you open a different issue and give more details about what have you done so far and what kind of error are you getting? 
This issue is about automating the addition of info to the iOS plist instead of changing it manually on the App_Resources

**Comment by francorobles** [comment]
Hi @AntonioCuevaUrraco . I fixed this already. There was a duplicate enty in my info.plist

**Comment by AntonioCuevaUrraco** [comment]
@francorobles Great!
