### ISSUE TITLE
FBSDKApplicationDelegate not exposed

### ISSUE THREAD

**Issue by shrink0r** [AntonioCuevaUrraco/nativescript-facebook-login#11]
Thx for providing this nice {N} plugin + example, as they are still scarce.
After following the setup steps I end up with the following error coming from the app.ios.js.
ReferenceError: Can't find variable: FBSDKApplicationDelegate
Being new to native-script I am not sure how to proceed to get the plugin running.
Thank you in advance

**Comment by shrink0r** [comment]
Started from scratch again.
Seems like the above issue might be resolved as soon as I get passed this new error: 

```
Processing node_modules failed. Error: Command failed: /bin/sh -c ruby -e "require 'xcodeproj'; xcproj = Xcodeproj::Project.open('challeng0r.xcodeproj'); xcproj.recreate_user_schemes; xcproj.save"
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

It pops up right after the plugin install.
If you have a quick idea, that would be awesome.
Guess you can close this otherwise.
Thx

**Comment by shrink0r** [comment]
Works now. \0/
Was missing the gems for xcodeproj and cocoapods.

**Comment by AntonioCuevaUrraco** [comment]
Glad it is working, everytime you install a plugin that is using some native library (Android or iOS) it may happen that it doesn't get expose to the platform and then you get this kind of errors. So you have to unplug and plug again or even remove the whole platform and add it again.
