### ISSUE TITLE
Android Error: FacebookActivity could not be started

### ISSUE THREAD

**Issue by victorhugom-zz** [AntonioCuevaUrraco/nativescript-facebook-login#12]
The plugin always throw this error. I tried to add the variables to the AndroidManifest inside the project or directly in the platforms/android/src/main/AndroidManifest, but this error keep showing

```
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
<activity android:name="com.facebook.FacebookActivity"
             android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
             android:theme="@android:style/Theme.Translucent.NoTitleBar"
             android:label="@string/app_name" 
             />
```

**Comment by AntonioCuevaUrraco** [comment]
Hello Victor, Sorry for the delay I was away for holidays. The code you shared seams to be all good.  
Do you have your facebook_app_id on the strings?  
Is the code inside the aplication?   

``` xml
 <application android:name="com.tns.NativeScriptApplication....
  ....
....
</application>
```

Can you call the native android sdk?
console.log(com.facebook.FacebookSdk.sdkInitialize());

If all that is working/on place I think we will have to look at the Facebook sdk level for a solution to your problem.

**Comment by AntonioCuevaUrraco** [comment]
Close due to inactivity
