### ISSUE TITLE
How to access user info

### ISSUE THREAD

**Issue by cagrias** [AntonioCuevaUrraco/nativescript-facebook-login#13]
Hi there, I'm trying to examine your plugin, is it possible to access the user info such as e-mail, gender etc. Thanks in advance.

**Comment by AntonioCuevaUrraco** [comment]
Is not implemented. The plugin is for login, and what you obtain in the result is the access token. With this access token you can call the Graph API and ask for user data.

In android is something like this:
http://stackoverflow.com/questions/29517667/android-facebook-sdk-4-x-how-to-get-email-address-and-facebook-access-token-to 
I can help you if you are interested in getting this expose to the .js

**Comment by cagrias** [comment]
Hi,

I've managed to get the details via Graph API as you said. The tricky part was to decide what info you want from Facebook by using setParameter function, which takes Bundle as argument. But I couldn't neither create a new Bundle instance nor access the current Bundle object from my current Activity so I called getParameters method of GraphRequest, cleared it, fill it and set it back, which solved the problem for now :)

**Comment by Tyre88** [comment]
"I can help you if you are interested in getting this expose to the .js" 

-Could you please do this?

**Comment by cagrias** [comment]
Hi,

You can find it from here in my repo:

https://github.com/cagrias/minder_mobile_js/blob/master/app/shared/view-model/user.js

The tricky part is to make another request after register by:
`var graphRequest = new com.facebook.GraphRequest.newMeRequest(result.getAccessToken(), graphCallback);`

Hope that helps!

**Comment by Tyre88** [comment]
Hi, i am having problem when i am trying to build the project now, it says: Cannot find name 'com'.

How do i include the "com.facebook" library? 

I've added "compile 'com.facebook.android:facebook-android-sdk:4.6.0'" to the build.grandle but it doesn't help. 

Also, will this work on iOS aswell?

**Comment by Tyre88** [comment]
This did the trick:
declare var com: any;

**Comment by cagrias** [comment]
I haven't used it on iOS yet.

**Comment by Tyre88** [comment]
To make these "GraphRequest" do i need to allow some kind of product on the facebook account? 

All builds now but when i make the request the callback isn't called.

My callback looks like this:

var graphCallback = new com.facebook.GraphRequest.GraphJSONObjectCallback({
            onCompleted: function(me, response) {
                if (response.getError() != null) {
                    console.log("ERROR: " + response.getError());
                } else {
                    console.log("ME: " + me);
                }
            },
            onError: function(error) {
                console.log("GRAPH ERROR: " + error);
            }
        });
