### ISSUE TITLE
Android hash key always does not match any stored key hashes

### ISSUE THREAD

**Issue by patuku-roy** [AntonioCuevaUrraco/nativescript-facebook-login#14]
Hi @AntonioCuevaUrraco ... When I run `tns run android` ... I can do a login through native dialogs but after that, the next page always show "Invalid key hash,. The key hash xxxxxxx does not match any stored key hashes.", I already removed and created a new app for several times and added the hash key like shown at error page, but the error still available. Any way to get the android debug hash key?

**Comment by AntonioCuevaUrraco** [comment]
It seams that the key hash for development is different that production and you have to add them both. Also in this thread people is saying:
"Facebook some how replaces +,- and / with _
So just try replacing _ with +, - and / and add that hash-key." 
http://stackoverflow.com/questions/19485004/android-app-key-hash-doesnt-match-any-stored-key-hashes

I hope that's your case and you can make it work

**Comment by patuku-roy** [comment]
@AntonioCuevaUrraco thanks for your reply, I will try to replace the hash key first ... let me check it

**Comment by patuku-roy** [comment]
@AntonioCuevaUrraco thanks, it works, but the reason is not about + and - characters. I put the wrong keystore alias when do `keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64` .. so this is my bad ..

But thanks anyway for the direction, I will close this issue.

**Comment by GamalSebaee** [comment]
@patuku-roy  i have same problem how i can solve it

**Comment by lucianbase** [comment]
This is how i solved this problem

Download your APK to your PC in java jdk\bin folder

in my case C:\Program Files\Java\jdk1.7.0_121\bin 

go to java jdk\bin folder and run cmd then
copy the following command in your cmd

keytool -list -printcert -jarfile yourapkname.apk

Copy the SHA1 value to your clip board
like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64. 
This is what Facebook requires
get the generated hash " ********************= " and copy the key hash to the facebook app.

**Comment by GamalSebaee** [comment]
Thanks Alot Sir

**Comment by haobk** [comment]
Thạn Alot @lucianbase

**Comment by AllARTSoftworks** [comment]
@lucianbase thank you, was going mad with this.

**Comment by farhansaid127** [comment]
This is how i solved this problem
I am using Firebase in my application,
I have got the SHA1 from firebase app -->project settings 

Copy the SHA1 value to your clip board
like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
This is what Facebook requires
get the generated hash " ********************= " and copy the key hash to the facebook app.

**Comment by matthiasprieth** [comment]
thanks @lucianbase thats working!

**Comment by Rockysarasimanalu** [comment]
thanks @lucianbase .... awesome

**Comment by Yugalmodi** [comment]
thanks @lucianbase It is the best way to create hash key. 
Please suggest the same method to facebook as well

**Comment by syafiq90** [comment]
Finally @lucianbase , thanks alot, awesome bro.

**Comment by Ajays786** [comment]
@lucianbase  thanks a  lot. sir

**Comment by SRV-Garg** [comment]
I checked by @lucianbase both the hash key are same but still getting the error "Facebook error: SERVER_ERROR: [code] 1349195 [message]: The key hash does not match any stored key hashes. Go to https://developers.facebook.com/docs/facebook-login/android for more information. [extra]: "
Any idea?

**Comment by SRV-Garg** [comment]
I found the solution, not the complete solution if you have facebook installed on your device then it will produce this error but if you uninstall the facebook app then it will work correctly but why this is happening and how can I resolve it please help

**Comment by PallaviSrivastava13** [comment]
> I found the solution, not the complete solution if you have facebook installed on your device then it will produce this error but if you uninstall the facebook app then it will work correctly but why this is happening and how can I resolve it please help

I am having the same issue did you find any solution?

**Comment by SRV-Garg** [comment]
> > I found the solution, not the complete solution if you have facebook installed on your device then it will produce this error but if you uninstall the facebook app then it will work correctly but why this is happening and how can I resolve it please help
> 
> I am having the same issue did you find any solution?

When you go for production then this problem doesn't exist.

**Comment by Yugalmodi** [comment]
Simple and best solution, What ever Key is coming in error page. Add the
same key in your Developer account.
I hope problem will be resolved.

Thanks,
Yugall Modi
Android Developer

reply from mobile

**Comment by PallaviSrivastava13** [comment]
> > > I found the solution, not the complete solution if you have facebook installed on your device then it will produce this error but if you uninstall the facebook app then it will work correctly but why this is happening and how can I resolve it please help
> > 
> > 
> > I am having the same issue did you find any solution?
> 
> When you go for production then this problem doesn't exist.

Yes You are right it worked for me

**Comment by mbabuskov** [comment]
I just had the same problem. The key was already there in the settings but it would only work for like 50% of the app users. I deleted the key and added the same key back and it started to work. Looks like some bug in Facebook authentication mechanism.

**Comment by Yugalmodi** [comment]
Yes there is some bugs in Facebook authentication. Sometimes it creates
problems. Specially when Facebook app is available in the testing device.

Thanks,
Yugall Modi
Android Developer

reply from mobile

**Comment by alexd555** [comment]
How can I fix it ?

**Comment by emailsubjekt** [comment]
Why isn't this fixed, I've had problems with this for months, some people can login and some can't, mostly those with loserbook app installed on their phone. I swear that's the worst company in the world with the worst product in the world.

**Comment by AshrafAlsmadi** [comment]
Just go firebase project setting and copy  last SHA certificate fingerprints and use this site to generate your hash key : 
http://tomeko.net/online_tools/hex_to_base64.php
#Happy_Coding

**Comment by MuhammadFaizan980** [comment]
@farhansaid127 ..your solution works perfectly (y)

**Comment by Brico2018** [comment]
> This is how i solved this problem
> 
> Download your APK to your PC in java jdk\bin folder
> 
> in my case C:\Program Files\Java\jdk1.7.0_121\bin
> 
> go to java jdk\bin folder and run cmd then
> copy the following command in your cmd
> 
> keytool -list -printcert -jarfile yourapkname.apk
> 
> Copy the SHA1 value to your clip board
> like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
> and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> This is what Facebook requires
> get the generated hash " ********************= " and copy the key hash to the facebook app.

thanks a lot

**Comment by RumsPatel** [comment]
> 
> 
> This is how i solved this problem
> 
> Download your APK to your PC in java jdk\bin folder
> 
> in my case C:\Program Files\Java\jdk1.7.0_121\bin
> 
> go to java jdk\bin folder and run cmd then
> copy the following command in your cmd
> 
> keytool -list -printcert -jarfile yourapkname.apk
> 
> Copy the SHA1 value to your clip board
> like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
> and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> This is what Facebook requires
> get the generated hash " ********************= " and copy the key hash to the facebook app.

Only this solution works for me. Thanks a lot. I was going mad .

**Comment by ghost** [comment]
Only this solution works for me. Thanks a lot.

> 
> 
> This is how i solved this problem
> 
> Download your APK to your PC in java jdk\bin folder
> 
> in my case C:\Program Files\Java\jdk1.7.0_121\bin
> 
> go to java jdk\bin folder and run cmd then
> copy the following command in your cmd
> 
> keytool -list -printcert -jarfile yourapkname.apk
> 
> Copy the SHA1 value to your clip board
> like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
> and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> This is what Facebook requires
> get the generated hash " ********************= " and copy the key hash to the facebook app.

**Comment by devmuaz** [comment]
@farhansaid127 thanks, solved my epic problem ..really

**Comment by admix26** [comment]
@lucianbase  thanks man, you saved my hours!

**Comment by ghost** [comment]
> This is how i solved this problem
> 
> Download your APK to your PC in java jdk\bin folder
> 
> in my case C:\Program Files\Java\jdk1.7.0_121\bin
> 
> go to java jdk\bin folder and run cmd then
> copy the following command in your cmd
> 
> keytool -list -printcert -jarfile yourapkname.apk
> 
> Copy the SHA1 value to your clip board
> like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
> and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> This is what Facebook requires
> get the generated hash " ********************= " and copy the key hash to the facebook app.
you are the one!

**Comment by a7vvmd** [comment]
> @AntonioCuevaUrraco thanks, it works, but the reason is not about + and - characters. I put the wrong keystore alias when do `keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64` .. so this is my bad ..
> 
> But thanks anyway for the direction, I will close this issue.

could you tell me how you solve it ? 
if ==> keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64 
this is the wrong command , then which one works for you?

**Comment by kishorpawar** [comment]
> @AntonioCuevaUrraco thanks, it works, but the reason is not about + and - characters. I put the wrong keystore alias when do `keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64` .. so this is my bad ..
> 
> But thanks anyway for the direction, I will close this issue.

I was also doing the same thing.


**_

**_DON'T BLINDLY COPY AND PASTE THE COMMAND GIVEN IN THE INSTRUCTIONS._**

_**

**Comment by mauryask** [comment]
> This is how i solved this problem
> I am using Firebase in my application,
> I have got the SHA1 from firebase app -->project settings
> 
> Copy the SHA1 value to your clip board
> like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
> and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> This is what Facebook requires
> get the generated hash " ********************= " and copy the key hash to the facebook app.

It really worked, Thanks a lot.
