### ISSUE TITLE
iOS not working despite adding FacebookAppID to info.plist

### ISSUE THREAD

**Issue by foliodev** [AntonioCuevaUrraco/nativescript-facebook-login#15]
**\* Terminating app due to uncaught exception 'InvalidOperationException', reason: 'App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].'

Ive added as mentioned above but still not working. im clueless. Android is working fine

**Comment by AntonioCuevaUrraco** [comment]
After modifying some plugin or adding/deleting some the client is going to create a new Info.plist 
Check that your Info.plist after building and running still contains the App ID.

So it would be like:   
- add the plugin
- tns prepare ios (plist is removed and added by the client)
- Modify that plist and run the project

If all that is useless for your case...which version of the client, core modules and platform are you using?

**Comment by foliodev** [comment]
Its working now. I just had to rename my app name it was initially 2 characters long now made it >3 characters coz i noticed the only diff was org.nativescript.demo and org.nativescript.aa and the demo was working.

So weird...but fixed it ROFL. Wasted 1/3 of my day on this. Was clueless lol.

Thanks for the reply by the way..

Could you please help me with rerequest permissions if they didnt allow all permissions?

 If `[FBSDKAccessToken currentAccessToken]` is not nil, it will be treated as a reauthorization for that user
  and will pass the "rerequest" flag to the login dialog.

How do i go about implementing this?

Thanks

**Comment by foliodev** [comment]
function init(loginBehavior) {
    loginManager = FBSDKLoginManager.alloc().init();
    if (loginManager) {
        //loginManager.logOut();

When i remove that line it seems like rerequest is working though im sure i will be breaking something else. I noted your comment     //This solve the case when user changes accounts error code 304.
Are there any better options?

I would appreciate your insight on this matter. Thanks

**Comment by AntonioCuevaUrraco** [comment]
The thing for logOut() is that if the user log in with FB account "A" then change that account to "B" and try to log in with B. Facebook still remember the login was done previously with A and return and error.
My idea is that the init method start everything clean, but we can add a method to request permissions.

I will try to put it together and add it to the update of plugin for the breaking changes on the CLI that are coming on 1.8 I would also appreciate help :-)
