### ISSUE TITLE
Plugin for many providers?

### ISSUE THREAD

**Issue by NathanWalker** [AntonioCuevaUrraco/nativescript-facebook-login#16]
Hi @AntonioCuevaUrraco ! Great work here.
I'm curious to begin work on a multi-provider plugin for Facebook, Google, Twitter, and probably Github as well.
Wondering if we should revamp things here for that? It would involve renaming the plugin, etc.
Or I may create a separate repo and we could migrate things there for this Facebook piece at least.
Thoughts?

**Comment by AntonioCuevaUrraco** [comment]
To use external sdks doesn't come without complications of something going wrong or https://github.com/NativeScript/nativescript-cli/issues/1542 that it is actually not really solved.

My idea is create a separate plugin for each provider and wrap them all into one as npm dependencies  for the people that want to use them all. I don't mind to make the API of the facebook plugin "more standard" so the calls from the multi-provider plugin are easier. 

You have all my support in working this out, right now Smarp app is using fb sdk and twitter and linkedin using the webview so there is a lot of room for us to work on this 

ping @rohitverma007

**Comment by AntonioCuevaUrraco** [comment]
ping @rohitverma007

**Comment by NathanWalker** [comment]
If the only issue was the "informational" app store message, that wouldn't be a blocker to a consolidated oauth plugin.
I have some ideas. Maybe we can chat on Slack over next couple days?

**Comment by NathanWalker** [comment]
Looks like bigger issue there though was on the Android side. Gotcha. Yeah, lets chat when possible.

**Comment by AntonioCuevaUrraco** [comment]
Well in android it stops building unless you enable multidex files :-/ for
example we reached the limit with around 10 plugins

**Comment by NathanWalker** [comment]
^ that's unfortunate :( Hopefully a solution will be found for that.

**Comment by AntonioCuevaUrraco** [comment]
Yes, and we can chat about the multi- connection plugin

**Comment by NathanWalker** [comment]
Just sent ya PM on slack. Whenever convenient for you.
