### ISSUE TITLE
Is it work in tns-core-modules@2.0.1?

### ISSUE THREAD

**Issue by katturajam** [AntonioCuevaUrraco/nativescript-facebook-login#19]
I am facing below mentioned problem

In FB Login ==> Confirm Page if Pressed  `OK` button ==>Expected to initiate callback: `successCallBack`  But Actaul what happening is app get minimized. 
If pressed `Cancel` button ==> Expected to close FB webview and goBack previous view But Actual what happening is app get minimized.

**Comment by AntonioCuevaUrraco** [comment]
I will be checking this issue today

**Comment by AntonioCuevaUrraco** [comment]
working
