### ISSUE TITLE
how to get user data from facebook after login

### ISSUE THREAD

**Issue by sunil123456** [AntonioCuevaUrraco/nativescript-facebook-login#22]
I am able to login with this plugin but how to get user's basic data after login??? 

var successCallback = function(result) {
             var token;
              if (topmost().android){
                token = result.getAccessToken().getToken();
              }
              else if (topmost().ios){
                token = result.token.tokenString
              }
          }

**Comment by AntonioCuevaUrraco** [comment]
@sunil123456 this plugin only covers the login, getting a token from facebook so you can identify the user.
On this issue one user got it to work but was never added to the plugin maybe is useful for you, https://github.com/AntonioCuevaUrraco/nativescript-facebook-login/issues/13
