### ISSUE TITLE
config app.ios

### ISSUE THREAD

**Issue by HoangJK** [AntonioCuevaUrraco/nativescript-facebook-login#23]
Hello,

I have a problem when config your plugin for ios. I have a project nativescript with angular2 and typescript. I don't know where's app.ios in my project, I just see main.ts file.

Regrads.

**Comment by AntonioCuevaUrraco** [comment]
@HoangJK You just need to configure the application lifecycle so the correct Facebook methods are called.

https://docs.nativescript.org/core-concepts/application-lifecycle#ios-uiapplicationdelegate

For ios you need to override 
- applicationDidFinishLaunchingWithOptions
- applicationOpenURLSourceApplicationAnnotation
- applicationDidBecomeActive
