### ISSUE TITLE
iOS not working

### ISSUE THREAD

**Issue by Tyre88** [AntonioCuevaUrraco/nativescript-facebook-login#27]
Hello,

When i've logged in to my facebook account in iOS i am propted to accept the rights and when i accept them i am left with a blank screen. I can click "Done" in the upper left corner but that fires the cancel callback. 

What to do?

**Comment by AntonioCuevaUrraco** [comment]
Hello, do you have the changes on the info.plist and on the application delegate?

It seams like a tricky problem, maybe some problem with the facebook app? are you able to log in on android?

**Comment by Tyre88** [comment]
The problem was that i did put the "application.ios.delegate = MyDelegate;" in the constructor of the angular module. 

I moved the delegate to be ran just before the bootstrap and it worked.
