### ISSUE TITLE
Problem after login

### ISSUE THREAD

**Issue by mounirka** [AntonioCuevaUrraco/nativescript-facebook-login#28]
Hi, i've installed the plugin on android and it works perfectly.
In my app i used the camera module to take a pic and also the imagepicker plugin, they both works if i don't call the facebook login before, but if i call it and then i try to take a pic it opens the camera but then it doesn't go inside the .then() promise. same thing for the imagepicker, it opens me the gallery to choose the pic but it returns nothing because it doesn't go inside the .then() promise.
Another problem was that if i call application.android.currentContext after the login, it contains something like com.FacebookActivity i think the two problems are related to each other.
Thank you for your help.

**Comment by mounirka** [comment]
After 2 days of digging i think i found where is the problem, but not the solution.
After the login process, when it returns to my app, the currentContext is equal to com.facebook.FacebookActivity@3b2a10e
`console.log(application.android.currentContext) //Result: com.facebook.FacebookActivity@3b2a10e`
When the currentContext is equal to com.tns.NativescriptActivity, everithing works.

**Comment by AntonioCuevaUrraco** [comment]
Hei @mounirka as NS change from one version to another things start behaving in a different way.

I have this kind of method in my app for other plugins on the callback function.

```ts
//  If we don't do this NS will not know which activity is the topmost
if (global.isAndroid) {
    applicationModule.android.currentContext = applicationModule.android.foregroundActivity || applicationModule.android.startActivity;
} 
```

Give it a try because to me it looks like the same problem and I can add it by default to the plugin if is the case. Also thank you for reporting

**Comment by mounirka** [comment]
Thank you for the reply @AntonioCuevaUrraco i tried to put the snippet but it doesn't work.
I noticed one strange thing and maybe it's the problem, look here
`function registerCallback(successCallback, cancelCallback, failCallback) {
if (_isInit) {
        var act = _AndroidApplication.foregroundActivity || _AndroidApplication.startActivity;
        _act = act;
        loginManager.registerCallback(mCallbackManager, new com.facebook.FacebookCallback({
            onSuccess: function (result) {
                successCallback(result);
            },
            onCancel: function () {
                cancelCallback();
            },
            onError: function (e) {
                failCallback(e);
            }
        }));
        act.onActivityResult = function (requestCode, resultCode, data) {
            console.log("Activity result is called"); //This line of code!
            mCallbackManager.onActivityResult(requestCode, resultCode, data);
        };
    }
}`
After the login, if i open the camera and take a picture, it calls the onActivityResult, but instead of returning the image, it logs "Activity result is called", this means that every time some activity returns it call the function assigned to act.onActivityResult. I think we have to find a way to return to the nativescriptActivity after the login process.
Thank you again.

**Comment by AntonioCuevaUrraco** [comment]
What about using this that is they way they do in the ns-core?:
```ts
let previousResult = act.onActivityResult;
act.onActivityResult = function (requestCode, resultCode, data) {
      appModule.android.onActivityResult = previousResult;
      mCallbackManager.onActivityResult(requestCode, resultCode, data);
};
```     

https://github.com/NativeScript/NativeScript/blob/16fb5865cb60e0947f0e3df5e1c141b5b68b68a4/tns-core-modules/camera/camera.android.ts

**Comment by mounirka** [comment]
Finally i found the solution, your snippet was almost right except for one line:
```
var previousResult = act.onActivityResult;
act.onActivityResult = function (requestCode, resultCode, data) {
         this.onActivityResult = previousResult; //This line is correct
         mCallbackManager.onActivityResult(requestCode, resultCode, data);
};
```
Instead of  appModule.android.onActivityResult you should call this.onActivityResult.
Now everything is working good, thank your for your time

**Comment by AntonioCuevaUrraco** [comment]
Ok good, I will move it to the plugin after I make some more test for other scenarios

**Comment by esavantsi** [comment]
Hi! I made a pull request which addresses this issue: #30
