### ISSUE TITLE
Open facebook in browser

### ISSUE THREAD

**Issue by mounirka** [AntonioCuevaUrraco/nativescript-facebook-login#29]
Hi, today i tried my app on an android device without the facebook app installed, and i expected that the browser will show on with the login page of facebook, but instead nothing happened and i just got the log with Login was cancelled.
Have you ever tried this feature, is it working? or maybe i'm just missing some piece of code in my manifest.xml?

Thank you again

**Comment by mounirka** [comment]
Ok i figured out the solution, i'll post the code here, so you can update the read me file.
In AndroidManifest.xml:
```
<activity 
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
	    android:exported="true"
            android:label="@string/app_name">
	        <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.DEFAULT" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <data android:scheme="@string/fb_login_protocol_scheme" />
                </intent-filter>
</activity>
```

And again in your AndroidManifest.xml set the launchMode to standard in your nativescriptActivity:
```
<activity
    android:name="com.tns.NativeScriptActivity"
    android:label="@string/title_activity_kimera"
    android:launchMode="standard"
    android:configChanges="keyboardHidden|orientation|screenSize"
    android:theme="@style/LaunchScreenTheme">
```

Finally in strings.xml add:
`<string name="fb_login_protocol_scheme">fb<replace_with_facebook_app_id></string>`

Now it should work perfectly :)

**Comment by AntonioCuevaUrraco** [comment]
ok, thanks
