### ISSUE TITLE
edit for the getting started readme - add a string

### ISSUE THREAD

**Issue by jlooper** [AntonioCuevaUrraco/nativescript-facebook-login#3]
It should be noted that you need to not only make changes to AndroidManifest.xml, but also to strings.xml where you place your facebook_app_id for Android:

platforms>android>src>main>res>strings.xml

```
<string name="facebook_app_id">your-app-id</string>
```

**Comment by AntonioCuevaUrraco** [comment]
Ups I forgot that one thanks. Added to the Readme
