### ISSUE TITLE
After facebook successfully login, How to get user Profile (Email,FirstName ...)

### ISSUE THREAD

**Issue by mawoole** [AntonioCuevaUrraco/nativescript-facebook-login#32]
Hi,

After facebook successfully login, in successCallback = function(result) { }, I can get current User facebook token (token = result.getAccessToken().getToken()) and UserID  .

Please, How to get user facebook Profile data (Email,FirstName,LastName ...) ?

**Comment by mounirka** [comment]
you have to send a GET request to graph API like this:
`https://graph.facebook.com/me?fields=id,name&access_token=[insert the access token]`

After field you can insert the data you want to get, you can see all the available fields [here](https://developers.facebook.com/docs/graph-api/reference/user)

**Comment by mawoole** [comment]
Ok, thanks
