### ISSUE TITLE
Login goes straight to "Not Logged In" splash screen with no login option.

### ISSUE THREAD

**Issue by ghost** [AntonioCuevaUrraco/nativescript-facebook-login#33]
I just figured out that I had to add the code snippets from the Readme into the App_Resources xml file, and now my login button works. However, instead of being prompted with a Facebook login screen, I see this, which lacks a login option. Is that just because it's on an emulator?

![desktop 01 18 2017 - 08 35 17 01](https://cloud.githubusercontent.com/assets/5335826/22066074/33b957b0-dd59-11e6-9cc8-e90bfd6b0025.png)

**Comment by mounirka** [comment]
Check the first answer given [here](http://stackoverflow.com/questions/31879804/you-are-not-logged-in-please-log-in-and-try-again)
