### ISSUE TITLE
Some example for Angular ?

### ISSUE THREAD

**Issue by ignaciolarranaga** [AntonioCuevaUrraco/nativescript-facebook-login#35]
Do you have some example for NativeScript / Angular ?

**Comment by AbdallahBedir** [comment]
+1

**Comment by chrillewoodz** [comment]
+1

**Comment by AntonioCuevaUrraco** [comment]
I never wrote a line of NativeScript + Angular. I don't think I am the right person to give you some demo. I will check Pull request if someone put one together

**Comment by mariano-aguero** [comment]
@AntonioCuevaUrraco you have a nativescript plugin, and you never wrote a line of code? Im really really sad

**Comment by AntonioCuevaUrraco** [comment]
@mariano-aguero I found some resources to help you

**Better reasons to be sad**: http://www.bbc.com/news
**Why am I so sad?**: http://kidshealth.org/en/kids/sadness.html
**How I can stop feeling sad?**  https://help.github.com/articles/creating-a-pull-request/
