### ISSUE TITLE
get information of user after login in facebook

### ISSUE THREAD

**Issue by ivanbuhov** [AntonioCuevaUrraco/nativescript-facebook-login#37]
_From @SumanSingh4 on February 20, 2017 11:49_

I have used nativescript-facebook-login  but it gives only access token. So i have tried to retrieve info through access-token but it gives only user-name and user-id.

Than i used nativescript-social-login but i am not successful in implementing. please help me in implementing.

_Copied from original issue: NativeScript/ios-runtime#728_

**Comment by AntonioCuevaUrraco** [comment]
https://github.com/AntonioCuevaUrraco/nativescript-facebook-login/issues/32

**Comment by ghost** [comment]
finally i got what i am searching for.
Thanxx a lot @AntonioCuevaUrraco
