### ISSUE TITLE
Odd behavior of Facebook Login in some devices like Nexus 6P

### ISSUE THREAD

**Issue by HamzaRehman** [AntonioCuevaUrraco/nativescript-facebook-login#38]
I'm currently making an app in NativeScript in which Facebook login is a needed feature. The problem is that in some devices, the plugin is working perfectly. In some others, it shows odd behavior (as follows)

1. The cancel callback is invoked on its own sometimes.
2. Other times, none of the three (success, failure and cancel) callbacks are invoked.

I'm using the plugin's code as follows,
```
FacebookLoginHandler.registerCallback(successCallback, cancelCallback, failCallback);
FacebookLoginHandler.logInWithReadPermissions(["email", "user_birthday", "public_profile"]);
```
There are log statements in the three callbacks. As mentioned above, sometimes the cancel callback's logs are printed and other times, nothing is printed.

The available background info as of now is that the app tries to login via Facebook using the Facebook app already installed in the phone.

Moreover, in my understanding, one solution to this could be to forcefully invoke the WebView Facebook Login even when the Facebook App is installed. If it is possible, can you share the necessary code for this strategy?

**Comment by AntonioCuevaUrraco** [comment]
function init(loginBehavior?: any):
loginBeahaviour is an int you can check facebook documents for android https://developers.facebook.com/docs/reference/android/current/class/LoginBehavior/
